# @package _global_

# This is a config for the joint_teleop.py script.
# It sets all the necessary parameters for the 6-DOF robot, teleoperator, and camera.

defaults:
  - _self_

robot:
  type: so101_6dof_follower
  port: /dev/ttyACM0
  use_degrees: true
  cameras:
    base_camera:
      type: opencv
      index_or_path: 2
      width: 640
      height: 360
      fps: 30

teleop:
  type: so101_6dof_leader
  port: /dev/ttyACM1
  use_degrees: true

frequency: 50.0
gripper_scale: 1.0 # This will be used in the script
display_data: true
